-- Generated by Oracle SQL Developer REST Data Services 22.2.1.234.1810
-- Exported REST Definitions from ORDS Schema Version 22.4.4.r0411526
-- Schema: MAJ   Date: Fri Mar 24 00:05:59 GMT 2023
--
BEGIN

  ORDS.DEFINE_MODULE(
      p_module_name    => 'file',
      p_base_path      => '/file/',
      p_items_per_page =>  0,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'file',
      p_pattern        => 'upload_download/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'file',
      p_pattern        => 'upload_download/',
      p_method         => 'GET',
      p_source_type    => 'resource/lob',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT content_type, content
FROM   media 
WHERE  file_name = :filename'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'file',
      p_pattern            => 'upload_download/',
      p_method             => 'GET',
      p_name               => 'filename',
      p_bind_variable_name => 'filename',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'file',
      p_pattern        => 'upload_download/',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'BEGIN
    INSERT INTO media (id,content_type,file_name,content) 
    VALUES (media_seq.NEXTVAL,:content_type,:filename,:body_text);

    :message:=''Success:''||:filename;
END;'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'file',
      p_pattern            => 'upload_download/',
      p_method             => 'POST',
      p_name               => 'filename',
      p_bind_variable_name => 'filename',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'file',
      p_pattern            => 'upload_download/',
      p_method             => 'POST',
      p_name               => 'message',
      p_bind_variable_name => 'message',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      


  COMMIT; 
END;